### PR TITLE
0.1.3

### PR DESCRIPTION
**Pull request by ca333**

### CODE REVIEW

**Comment by ca333** [comment]
> 2. negative BTC input when balance is too low (need an additional check in the frontend to be sure to not call backend function if we don't have balance > minimal_trade_balance)

likely makes sense to add a sanity check to ensure this can not happen backend-side @Milerius

**Comment by naezith** [comment]
> 1. Can't paste ETH address when sending

https://github.com/KomodoPlatform/atomicDEX-Pro/pull/157

**Comment by naezith** [comment]
> 2. negative BTC input when balance is too low (need an additional check in the frontend to be sure to not call backend function if we don't have balance > minimal_trade_balance)

https://github.com/KomodoPlatform/atomicDEX-Pro/pull/159

**Comment by Milerius** [comment]
@ca333 Yeah that's added on both, let's merge #160 #159 #157 and we are ready to bundle/release

**Comment by ca333** [comment]
@tonymorony execute full test and provide us QA signoff

**Pull request merged**
