### PR TITLE
Privacy UI

### PR DESCRIPTION
**Pull request by naezith**
Implements https://github.com/KomodoPlatform/atomicDEX-Pro/issues/332

Half of this feature was implemented at `naezith_dev` already. It is complete with these changes.

The DEX page does not have privacy.

I can hide more stuff if requested, here is the current look:

image
image
image
image
image

### CODE REVIEW

**Comment by tonymorony** [comment]
The balances are visible atm trough base coin selector:
image

I think it's logical for this feature to hide these numbers as well

**Comment by naezith** [comment]
Amount input and MAX slider are still visible. DEX section won't be usable if we do this. Binance does not have an option to hide stuff at the trade page.

These are the reasons why I didn't take that action.

**Comment by tonymorony** [comment]
> Amount input and MAX slider are still visible. DEX section won't be usable if we do this. Binance does not have an option to hide stuff at the trade page.
> 
> These are the reasons why I didn't take that action.

I see, in such case there is no much sense to hide information on Orders and History pages

I think it might be worth to consult with @ca333 - I realised that don't understand on 100% that particular feature practical sense

**Comment by naezith** [comment]
> I see, in such case there is no much sense to hide information on Orders and History pages

I think that's still good because you can still see the date, result, and names/icons of the coins.

**Comment by Milerius** [comment]
I'm merging this one, at the worst case we will open enhancement issues. (The main feature is present and working, and the following change are needed to implement addressbook)

**Comment by ca333** [comment]
> I'm merging this one, at the worst case we will open enhancement issues. (The main feature is present and working, and the following change are needed to implement addressbook)

it seems this was merged although a question from https://github.com/KomodoPlatform/atomicDEX-Pro/pull/352#issuecomment-657203489 was still open - plz ensure this does not happen again. Open questions or outstanding approvals from Tony are equal and essential requirement for merging @Milerius !

**Pull request merged**
