### PR TITLE
Add LABS coin

### PR DESCRIPTION
**Pull request by zatJUM**

### CODE REVIEW

**Comment by Milerius** [comment]
@zatJUM Missing png file of the coins in the coins img folder and qrc file

**Comment by zatJUM** [comment]
Sorry, I really have to learn how to use git from cli: I can't find how to do what I want from github :-(
I don't know how to change my commit from this branch to dev branch (on github).
I've searched the spec of the image coin, but couldn't find them, so I've copied an old one (kmd.png) and tried to convert labs.png to the same specs (locally), but none of my tries succeeded.
At last, I don't find what a qrc file should look like: couldn't find one for existing coins.

**Comment by Milerius** [comment]
Just drop the labs.png here @zatJUM I will add it on your branch

**Comment by zatJUM** [comment]
labs
Uploading the best quality I have... Thanks

**Comment by Milerius** [comment]
#95

**Comment by ca333** [comment]
#97

**Pull request closed without merging**
