### PR TITLE
enhancements(trading): big refactor trading backend

### PR DESCRIPTION
**Pull request by Milerius**

### CODE REVIEW

**Comment by tonymorony** [comment]
notes so far:

1) expedient widget breaking after arrows usage for pairs with USD evaluation:

image

2)

it's still possible to get random values on expedient widget for assets without USD value if you select one order, then press arrows, then select order again

image

3) on notification click app window resizing: 
https://drive.google.com/file/d/1n2b3Q4k-a6CNt68KPLrfGPcANAAp1bSZ/view?usp=sharing

4) it's possible to start swap with custom security settings with both notas and confirmations settings disabled what is quite confusing

2wg3F8kd1M

if you disable dPoW switch - confirmations switch should enable at this time (one of cond for these switches)

**Comment by smk762** [comment]
URLs leading to error as mentioned in https://github.com/KomodoPlatform/atomicDEX-Pro/issues/381 are still failing (I understand this might be addressed in a different branch).

**Comment by tonymorony** [comment]
> URLs leading to error as mentioned in #381 are still failing (I understand this might be addressed in a different branch).

this issue was not fixed in that PR, it's expected that it works as before

**Comment by smk762** [comment]
CEX rate seems to break when selecting same coin as active in opposite dropdown.
To reproduce, go to dex screen, select "Dash" on left drop down, then select "Dash" on right dropdown. This triggers change in left dropdown (in my case to DOGE), then CEX exchange rate reports `1 DASH = 1 DOGE`
Peek 2020-08-10 19-53

**Comment by smk762** [comment]
Simple feature request: Currently Fiat options list is unsorted. Can this be made alphabetical (maybe with major currencies at top for convenience, followed by others)
image

Coingecko options are an example of the major/other option split - 
image

Adding full currency name might look nice also, but probably people will know what they are looking for anyway without it.

**Comment by tonymorony** [comment]
> Simple feature request: Currently Fiat options list is unsorted. Can this be made alphabetical (maybe with major currencies at top for convenience, followed by others)
> image
> 
> Coingecko options are an example of the major/other option split -
> image
> 
> Adding full currency name might look nice also, but probably people will know what they are looking for anyway without it.

thats good feature request. however. please create separate issue ticket not PR comment

**Comment by smk762** [comment]
feat(gui): remove the unnecessary `change required confirmations` switch sighted and confirmed displaying as intended on Linux (for viewed subset of  smartchain pairs excluding the below)

MCL & VRSC are dPoW protected, but this option not visible for KMD -> VRSC or KMD -> MCL swaps

image
image

**Comment by smk762** [comment]
`1 DASH = 1 DOGE` issue https://github.com/KomodoPlatform/atomicDEX-Pro/pull/415#issuecomment-671312993
resolved, selecting same coin in opposite dropdown now updates exchange rate correctly.

**Pull request merged**
