### PR TITLE
Toggle currency on banner click

### PR DESCRIPTION
**Pull request by naezith**
Implements https://github.com/KomodoPlatform/atomicDEX-Pro/issues/331

### CODE REVIEW

**Comment by tonymorony** [comment]
Endless "Loading" on my side (tried OSX dmg from this build https://github.com/KomodoPlatform/atomicDEX-Pro/actions/runs/162150984)
log: https://paste.ubuntu.com/p/q5NpNWBytv/

image

**Comment by tonymorony** [comment]
Looks good, however at the moment it works not as: `selected Fiat / BTC / KMD` but as `USD / BTC / EUR / KMD`

@naezith Please use only one fiat currency selected in Settings -> Fiat with only fiat currencies in that list:

image

**Comment by naezith** [comment]
@Milerius backend needs to change for this last request because those 4 are in `get_available_fiats`.

**Comment by tonymorony** [comment]
On startup ticker is Undefined atm, until I click the toggle

```
[22:04:59 +07:00] [I] [thr 13026] refreshing transactions
[22:04:59 +07:00] [D] [thr 13026] refresh_transactions l322
[22:04:59 +07:00] [W] [thr 13026] error when converting BTC to USD, err: You try to convert from an unknown ticker, are you trying to convert from a test-coin ?
[22:04:59 +07:00] [W] [thr 13026] error when converting KMD to USD, err: You try to convert from an unknown ticker, are you trying to convert from a test-coin ?
[22:04:59 +07:00] [W] [thr 13026] error when converting ZEC to USD, err: You try to convert from an unknown ticker, are you trying to convert from a test-coin ?
```

image

**Comment by naezith** [comment]
Front-end did not apply the back-end changes yet.

**Comment by naezith** [comment]
Should be fine now.

**Pull request merged**
