### PR TITLE
French translation updates

### PR DESCRIPTION
**Pull request by zatJUM**

### CODE REVIEW

**Comment by Milerius** [comment]
Hey did you use QT Linguis tool for udpating language UI elements ?

**Comment by zatJUM** [comment]
No, I 'git pull'ed dev branch and edited file with vim

**Comment by Milerius** [comment]
@zatJUM Mostly because the tool will tell you if an errors occurs during the translation / if you respect the format. i would prefer if you can check with the software if everything is fine !

**Comment by Milerius** [comment]
UI Will change a lot, and will broke almost all translation part, I'm closing it for the moment.

**Pull request closed without merging**
